/*
 * CostomersDPanel.java
 *
 * Created on 22 Август 2008 г., 0:46
 */
package tradeterminal.references_books.customers;

import java.awt.Dimension;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import minersinstrument.db.PAJDBCComboBoxModel;
import minersinstrument.ui.IADialogPanel;
import org.postgresql.ds.PGPoolingDataSource;
import tradeterminal.Setup;

/**
 *
 * @author  pacman
 */
public class CostomersDPanel extends javax.swing.JPanel implements IADialogPanel {

    class DocTypesComboBoxModel extends PAJDBCComboBoxModel {

        public DocTypesComboBoxModel(PGPoolingDataSource source) {
            super(source);
        }

        protected PAJDBCCResult vExecuteQuery(Connection conn) throws SQLException {
            conn.setAutoCommit(false);

            CallableStatement proc = conn.prepareCall("{ ? = call rb_doc_types_select() }");
            proc.registerOutParameter(1, Types.OTHER);

            proc.execute();

            return new PAJDBCCResult((ResultSet) proc.getObject(1), conn, proc);
        }
    }
    private DocTypesComboBoxModel docTypesComboBoxModel = new DocTypesComboBoxModel(Setup.getSource());

    /** Creates new form CostomersDPanel */
    public CostomersDPanel() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));

        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane2.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));


        docTypeComboBox.setModel(docTypesComboBoxModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        shortNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fioTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adressTextPane = new javax.swing.JTextPane();
        sexComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        phoneNumber2TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        docTypeComboBox = new javax.swing.JComboBox();
        docTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        urFRadioButton = new javax.swing.JRadioButton();
        urURadioButton = new javax.swing.JRadioButton();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(CostomersDPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        shortNameTextField.setText(resourceMap.getString("shortNameTextField.text")); // NOI18N
        shortNameTextField.setName("shortNameTextField"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        fioTextField.setText(resourceMap.getString("fioTextField.text")); // NOI18N
        fioTextField.setName("fioTextField"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        adressTextPane.setName("adressTextPane"); // NOI18N
        jScrollPane1.setViewportView(adressTextPane);

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Мужской", "Женский"}));
        sexComboBox.setName("sexComboBox"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        phoneNumberTextField.setText(resourceMap.getString("phoneNumberTextField.text")); // NOI18N
        phoneNumberTextField.setName("phoneNumberTextField"); // NOI18N

        phoneNumber2TextField.setText(resourceMap.getString("phoneNumber2TextField.text")); // NOI18N
        phoneNumber2TextField.setName("phoneNumber2TextField"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        emailTextField.setText(resourceMap.getString("emailTextField.text")); // NOI18N
        emailTextField.setName("emailTextField"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        docTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));
        docTypeComboBox.setName("docTypeComboBox"); // NOI18N

        docTextField.setText(resourceMap.getString("docTextField.text")); // NOI18N
        docTextField.setName("docTextField"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setName("descriptionTextArea"); // NOI18N
        jScrollPane2.setViewportView(descriptionTextArea);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        buttonGroup1.add(urFRadioButton);
        urFRadioButton.setSelected(true);
        urFRadioButton.setText(resourceMap.getString("urFRadioButton.text")); // NOI18N
        urFRadioButton.setName("urFRadioButton"); // NOI18N

        buttonGroup1.add(urURadioButton);
        urURadioButton.setText(resourceMap.getString("urURadioButton.text")); // NOI18N
        urURadioButton.setName("urURadioButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jLabel9).addComponent(jLabel6).addComponent(jLabel5).addComponent(jLabel4).addComponent(jLabel3).addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jLabel8).addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE).addComponent(jLabel7)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(docTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE).addGroup(layout.createSequentialGroup().addComponent(urFRadioButton).addGap(18, 18, 18).addComponent(urURadioButton)).addComponent(shortNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE).addComponent(fioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE).addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE).addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE).addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false).addComponent(phoneNumber2TextField, javax.swing.GroupLayout.Alignment.LEADING).addComponent(sexComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(phoneNumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)).addComponent(docTypeComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 329, Short.MAX_VALUE)).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(docTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8).addComponent(docTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(urFRadioButton).addComponent(urURadioButton)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(shortNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel1)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2).addComponent(fioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4).addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel5)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(phoneNumber2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6).addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel9).addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    public String getAdress() {
        return adressTextPane.getText();
    }

    public void setAdress(String s) {
        this.adressTextPane.setText(s);
    }

    public String getDescription() {
        return descriptionTextArea.getText();
    }

    public void setDescription(String s) {
        this.descriptionTextArea.setText(s);
    }

    public String getDoc() {
        return docTextField.getText();
    }

    public void setDoc(String s) {
        this.docTextField.setText(s);
    }

    public int getDocType() {
        return docTypesComboBoxModel.getSelectedRowId();
    }

    public String getDocTypeName() {
        return docTypesComboBoxModel.getSelectedRowName();
    }

    public void setDocType(int id) {
        this.docTypesComboBoxModel.setSelectedRowId(id);
    }

    public String getEmail() {
        return emailTextField.getText();
    }

    public void setEmail(String s) {
        this.emailTextField.setText(s);
    }

    public String getFio() {
        return fioTextField.getText();
    }

    public void setFio(String s) {
        this.fioTextField.setText(s);
    }

    public String getPhoneNumber2() {
        return phoneNumber2TextField.getText();
    }

    public void setPhoneNumber2(String s) {
        this.phoneNumber2TextField.setText(s);
    }

    public String getPhoneNumber() {
        return phoneNumberTextField.getText();
    }

    public void setPhoneNumber(String s) {
        this.phoneNumberTextField.setText(s);
    }

    public int getSex() {
        return sexComboBox.getSelectedIndex();
    }

    public void setSex(int sex) {
        this.sexComboBox.setSelectedIndex(sex);
    }

    public String getShortName() {
        return shortNameTextField.getText();
    }

    public void setShortName(String s) {
        this.shortNameTextField.setText(s);
    }

    public Boolean getUrURadioButton() {
        return urURadioButton.isSelected();
    }

    public void setUrURadioButton(Boolean b) {
        this.urURadioButton.setSelected(b);
    }

    public boolean checkPanel() {
        return true;
    }

    public void openPanel() {
        docTypeComboBox.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane adressTextPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JTextField docTextField;
    private javax.swing.JComboBox docTypeComboBox;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField fioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField phoneNumber2TextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JComboBox sexComboBox;
    private javax.swing.JTextField shortNameTextField;
    private javax.swing.JRadioButton urFRadioButton;
    private javax.swing.JRadioButton urURadioButton;
    // End of variables declaration//GEN-END:variables
}
