/*
 * ReportsMainPanel.java
 *
 * Created on 5 Май 2008 г., 12:08
 */
package tradeterminal.reports;

import java.awt.BorderLayout;
import java.awt.Component;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import net.sf.jasperreports.swing.*;
import org.jdesktop.application.Action;
import tradeterminal.IPage;
import tradeterminal.reports.customer_history.CustomerHistory;
import tradeterminal.reports.orders_history.OrdersHistory;
import tradeterminal.reports.product_movong.ProductMoving;
import tradeterminal.reports.ppl_for_date.PPLForDate;
import tradeterminal.reports.psl_for_date.PSLForDate;
import tradeterminal.reports.tov_obor_for_date_scod.TovOborForDateScode;
import tradeterminal.reports.z.ZOBForDate;
import tradeterminal.reports.z.ZReport;

/**
 *
 * @author  PKopychenko
 */
public class ReportsMainPanel extends javax.swing.JPanel implements IPage {

    /** Creates new form ReportsMainPanel */
    public ReportsMainPanel() {

        initComponents();



        JRViewer jv = new JRViewer(null);

        add(jv, BorderLayout.CENTER);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink8 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink5 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink6 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane4 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();
        jXTaskPane5 = new org.jdesktop.swingx.JXTaskPane();
        jXHyperlink7 = new org.jdesktop.swingx.JXHyperlink();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout(4, 4));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(ReportsMainPanel.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jXTaskPaneContainer1.setName("jXTaskPaneContainer1"); // NOI18N

        jXTaskPane1.setIcon(resourceMap.getIcon("jXTaskPane1.icon")); // NOI18N
        jXTaskPane1.setName("jXTaskPane1"); // NOI18N
        jXTaskPane1.setTitle(resourceMap.getString("jXTaskPane1.title")); // NOI18N
        jXTaskPane1.setLayout(new org.jdesktop.swingx.VerticalLayout());

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getActionMap(ReportsMainPanel.class, this);
        jXHyperlink1.setAction(actionMap.get("makeZReport")); // NOI18N
        jXHyperlink1.setIcon(resourceMap.getIcon("jXHyperlink1.icon")); // NOI18N
        jXHyperlink1.setText(resourceMap.getString("jXHyperlink1.text")); // NOI18N
        jXHyperlink1.setName("jXHyperlink1"); // NOI18N
        jXTaskPane1.add(jXHyperlink1);

        jXHyperlink4.setAction(actionMap.get("createZForPeriod")); // NOI18N
        jXHyperlink4.setIcon(resourceMap.getIcon("jXHyperlink4.icon")); // NOI18N
        jXHyperlink4.setName("jXHyperlink4"); // NOI18N
        jXTaskPane1.add(jXHyperlink4);

        jXHyperlink8.setAction(actionMap.get("psl_for_date")); // NOI18N
        jXHyperlink8.setIcon(resourceMap.getIcon("jXHyperlink8.icon")); // NOI18N
        jXHyperlink8.setText(resourceMap.getString("jXHyperlink8.text")); // NOI18N
        jXHyperlink8.setName("jXHyperlink8"); // NOI18N
        jXTaskPane1.add(jXHyperlink8);

        jXTaskPaneContainer1.add(jXTaskPane1);

        jXTaskPane3.setIcon(resourceMap.getIcon("jXTaskPane3.icon")); // NOI18N
        jXTaskPane3.setName("jXTaskPane3"); // NOI18N
        jXTaskPane3.setTitle(resourceMap.getString("jXTaskPane3.title")); // NOI18N
        jXTaskPane3.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXHyperlink2.setAction(actionMap.get("productMoving")); // NOI18N
        jXHyperlink2.setIcon(resourceMap.getIcon("jXHyperlink2.icon")); // NOI18N
        jXHyperlink2.setText(resourceMap.getString("jXHyperlink2.text")); // NOI18N
        jXHyperlink2.setName("jXHyperlink2"); // NOI18N
        jXTaskPane3.add(jXHyperlink2);

        jXHyperlink5.setAction(actionMap.get("obor_tov_for_code")); // NOI18N
        jXHyperlink5.setIcon(resourceMap.getIcon("jXHyperlink5.icon")); // NOI18N
        jXHyperlink5.setText(resourceMap.getString("jXHyperlink5.text")); // NOI18N
        jXHyperlink5.setName("jXHyperlink5"); // NOI18N
        jXTaskPane3.add(jXHyperlink5);

        jXHyperlink6.setAction(actionMap.get("ppl_for_date")); // NOI18N
        jXHyperlink6.setIcon(resourceMap.getIcon("jXHyperlink6.icon")); // NOI18N
        jXHyperlink6.setText(resourceMap.getString("jXHyperlink6.text")); // NOI18N
        jXHyperlink6.setName("jXHyperlink6"); // NOI18N
        jXTaskPane3.add(jXHyperlink6);

        jXTaskPaneContainer1.add(jXTaskPane3);

        jXTaskPane4.setIcon(resourceMap.getIcon("jXTaskPane4.icon")); // NOI18N
        jXTaskPane4.setName("jXTaskPane4"); // NOI18N
        jXTaskPane4.setTitle(resourceMap.getString("jXTaskPane4.title")); // NOI18N
        jXTaskPane4.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXHyperlink3.setAction(actionMap.get("createOrdersHistoryReport")); // NOI18N
        jXHyperlink3.setIcon(resourceMap.getIcon("jXHyperlink3.icon")); // NOI18N
        jXHyperlink3.setName("jXHyperlink3"); // NOI18N
        jXTaskPane4.add(jXHyperlink3);

        jXTaskPaneContainer1.add(jXTaskPane4);

        jXTaskPane5.setIcon(resourceMap.getIcon("jXTaskPane5.icon")); // NOI18N
        jXTaskPane5.setName("jXTaskPane5"); // NOI18N
        jXTaskPane5.setTitle(resourceMap.getString("jXTaskPane5.title")); // NOI18N
        jXTaskPane5.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXHyperlink7.setAction(actionMap.get("customer_history")); // NOI18N
        jXHyperlink7.setIcon(resourceMap.getIcon("jXHyperlink7.icon")); // NOI18N
        jXHyperlink7.setText(resourceMap.getString("jXHyperlink7.text")); // NOI18N
        jXHyperlink7.setName("jXHyperlink7"); // NOI18N
        jXTaskPane5.add(jXHyperlink7);

        jXTaskPaneContainer1.add(jXTaskPane5);

        jPanel1.add(jXTaskPaneContainer1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    /***
     * Функция отображения отчета в центре панели 
     * @param ir
     */
    private void make(IReport ir) {

        try {
            Component c = ir.makeReport();

            if (c == null) {
                return;
            } else {
                remove(1);
                add(c, BorderLayout.CENTER);
                updateUI();
            }
        } catch (Exception ex) {
            Logger.getLogger(ReportsMainPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void updateContent() {
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public Icon getCaptionIcon() {
        return new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/additional/2.png"));
    }

    public String getCaptionText() {
        return "Отчет";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink6;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink7;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink8;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane4;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane5;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    // End of variables declaration//GEN-END:variables

    /***
     * Возвращает динамческое меню
     * @return
     */
    public List<JMenuItem> getMenuItemList() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Action
    public void makeZReport() {
        System.out.println("Z-отчет");
        make(new ZReport());
    }

    @Action
    public void createOrdersHistoryReport() {
        make(new OrdersHistory());
    }

    @Action
    public void createOperationInfoReport() {
    }

    @Action
    public void productMoving() {
        make(new ProductMoving());
    }

    @Action
    public void createZForPeriod() {
        make(new ZOBForDate());
    }

    /**
     * Продажа за время
     */
    @Action
    public void psl_for_date() {
        make(new PSLForDate());
    }

    @Action
    public void obor_tov_for_code() {
        make(new TovOborForDateScode());
    }

    @Action
    public void ppl_for_date() {
        make(new PPLForDate());
    }

    @Action
    public void customer_history() {
         make(new CustomerHistory());
    }
}
