/*
 * 
 * ProductDiscountBaseDPanel.java
 *
 * Created on 28 Март 2008 г., 12:06
 */
package tradeterminal.operations.products.selling.base;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.text.ParseException;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import minersinstrument.ui.IADialogPanel;
import org.codehaus.groovy.runtime.typehandling.BigDecimalMath;

/**
 *
 * @author  PKopychenko
 */
public abstract class ProductDiscountBaseDPanel extends javax.swing.JPanel implements IADialogPanel {

    protected double list_price = 0;
    protected double maximum = 0;
    protected double minimum = 0;

    /** Creates new form ProductDiscountBaseDPanel */
    public ProductDiscountBaseDPanel(double list_price, double value, double minimum, double maximum, double stepSize) {
        initComponents();

        this.list_price = list_price;
        list_priceFormattedTextField.setValue(list_price);

        this.maximum = maximum;
        this.minimum = minimum;

        SpinnerNumberModel sm = new SpinnerNumberModel(
                Double.valueOf(value),
                Double.valueOf(minimum),
                Double.valueOf(maximum),
                Double.valueOf(stepSize));

        valueSpinner.setModel(sm);

        bVLabel.setText(Double.toString(minimum));
        eVLabel.setText(Double.toString(maximum));

        valueSlider.setMinimum(new BigDecimal(Math.round(minimum)).intValue());
        valueSlider.setMaximum(new BigDecimal(Math.round(maximum)).intValue());

        final DefaultEditor de = (DefaultEditor) valueSpinner.getEditor();

        de.getTextField().addCaretListener(new javax.swing.event.CaretListener() {

            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                try {
                    NumberFormat nf = java.text.DecimalFormat.getInstance();
                    valueSlider.setValue(new BigDecimal(Math.round(nf.parse(de.getTextField().getText()).doubleValue())).intValue());
                    calculate();
                } catch (Exception ex) {
                }
            }
        });

        valueSlider.addChangeListener(new ChangeListener() {

            public void stateChanged(ChangeEvent e) {
                if (valueSlider.isFocusOwner()) {
                    valueSpinner.setValue((double) valueSlider.getValue());
                    calculate();
                }
            }
        });

        valueSpinner.setValue(value);
        valueSlider.setValue(new BigDecimal(Math.round(value)).intValue());
        calculate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prefixLabel = new javax.swing.JLabel();
        valueSpinner = new javax.swing.JSpinner();
        suffixLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        valueSlider = new javax.swing.JSlider();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        discontPriceFormattedTextField = new javax.swing.JFormattedTextField();
        currencyNameLabel2 = new javax.swing.JLabel();
        bVLabel = new javax.swing.JLabel();
        eVLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        list_priceFormattedTextField = new javax.swing.JFormattedTextField();
        currencyNameLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(ProductDiscountBaseDPanel.class);
        prefixLabel.setText(resourceMap.getString("prefixLabel.text")); // NOI18N
        prefixLabel.setName("prefixLabel"); // NOI18N

        valueSpinner.setFont(resourceMap.getFont("valueSpinner.font")); // NOI18N
        valueSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), Float.valueOf(101.0f), Float.valueOf(0.1f)));
        valueSpinner.setName("valueSpinner"); // NOI18N
        valueSpinner.setPreferredSize(new java.awt.Dimension(80, 18));

        suffixLabel.setText(resourceMap.getString("suffixLabel.text")); // NOI18N
        suffixLabel.setName("suffixLabel"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(39, 39, 39).addComponent(prefixLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(valueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(suffixLabel).addGap(41, 41, 41)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(5, 5, 5).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(valueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(suffixLabel).addComponent(prefixLabel))));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout(5, 5));

        valueSlider.setMajorTickSpacing(10);
        valueSlider.setMinorTickSpacing(1);
        valueSlider.setPaintLabels(true);
        valueSlider.setPaintTicks(true);
        valueSlider.setSnapToTicks(true);
        valueSlider.setMinimumSize(new java.awt.Dimension(200, 46));
        valueSlider.setName("valueSlider"); // NOI18N
        jPanel2.add(valueSlider, java.awt.BorderLayout.CENTER);

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(180, 14));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        discontPriceFormattedTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        discontPriceFormattedTextField.setEditable(false);
        discontPriceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        discontPriceFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        discontPriceFormattedTextField.setFont(resourceMap.getFont("discontPriceFormattedTextField.font")); // NOI18N
        discontPriceFormattedTextField.setName("discontPriceFormattedTextField"); // NOI18N
        discontPriceFormattedTextField.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel7.add(discontPriceFormattedTextField, java.awt.BorderLayout.CENTER);

        currencyNameLabel2.setText(resourceMap.getString("currencyNameLabel2.text")); // NOI18N
        currencyNameLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        currencyNameLabel2.setName("currencyNameLabel2"); // NOI18N
        jPanel7.add(currencyNameLabel2, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        bVLabel.setText(resourceMap.getString("bVLabel.text")); // NOI18N
        bVLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        bVLabel.setName("bVLabel"); // NOI18N
        jPanel2.add(bVLabel, java.awt.BorderLayout.LINE_START);

        eVLabel.setText(resourceMap.getString("eVLabel.text")); // NOI18N
        eVLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        eVLabel.setName("eVLabel"); // NOI18N
        jPanel2.add(eVLabel, java.awt.BorderLayout.LINE_END);

        add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 14));
        jPanel3.add(jLabel1, java.awt.BorderLayout.WEST);

        list_priceFormattedTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        list_priceFormattedTextField.setEditable(false);
        list_priceFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        list_priceFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        list_priceFormattedTextField.setFont(resourceMap.getFont("list_priceFormattedTextField.font")); // NOI18N
        list_priceFormattedTextField.setName("list_priceFormattedTextField"); // NOI18N
        list_priceFormattedTextField.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel3.add(list_priceFormattedTextField, java.awt.BorderLayout.CENTER);

        currencyNameLabel1.setText(resourceMap.getString("currencyNameLabel1.text")); // NOI18N
        currencyNameLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        currencyNameLabel1.setName("currencyNameLabel1"); // NOI18N
        jPanel3.add(currencyNameLabel1, java.awt.BorderLayout.EAST);

        add(jPanel3, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    public void setCurency(String s) {
        currencyNameLabel1.setText(s);
        currencyNameLabel2.setText(s);
    }

    public void setSuffixText(String s) {
        suffixLabel.setText(s);
        bVLabel.setText(Double.toString(minimum) + s);
        eVLabel.setText(Double.toString(maximum) + s);
    }

    abstract public void calculate();

    public boolean checkPanel() {
        try {
            valueSpinner.commitEdit();

            return true;
        } catch (ParseException ex) {
            return false;
        }
    }

    public void openPanel() {
    }

    public double getDiscountValue() {
        return (Double) valueSpinner.getValue();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bVLabel;
    private javax.swing.JLabel currencyNameLabel1;
    private javax.swing.JLabel currencyNameLabel2;
    protected javax.swing.JFormattedTextField discontPriceFormattedTextField;
    private javax.swing.JLabel eVLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    protected javax.swing.JFormattedTextField list_priceFormattedTextField;
    protected javax.swing.JLabel prefixLabel;
    protected javax.swing.JLabel suffixLabel;
    protected javax.swing.JSlider valueSlider;
    protected javax.swing.JSpinner valueSpinner;
    // End of variables declaration//GEN-END:variables
}
