/*
 * UsersControlPanel.java
 *
 * Created on 17 Февраль 2008 г., 13:17
 */
package tradeterminal.users;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import minersinstrument.ui.AUniversalDialog;
import org.jdesktop.application.Action;
import tradeterminal.Setup;
import tradeterminal.users.accesssetup.AccessSetup;

/**
 *
 * @author  kopychenko
 */
public class UsersMainPanel extends javax.swing.JPanel {

    UsersAdapter adapter = new UsersAdapter(Setup.getSource());

    /** Creates new form UsersControlPanel */
    public UsersMainPanel() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));

        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane2.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));


        userTable.setAdapter(adapter);

        userTable.getColumnModel().removeColumn(userTable.getColumnModel().getColumn(0));
        userTable.getColumnModel().removeColumn(userTable.getColumnModel().getColumn(1));
        userTable.getColumnModel().removeColumn(userTable.getColumnModel().getColumn(2));

        userTable.getColumnModel().getColumn(0).setPreferredWidth(150);
        userTable.getColumnModel().getColumn(0).setHeaderValue("Имя");
        userTable.getColumnModel().getColumn(1).setPreferredWidth(90);
        userTable.getColumnModel().getColumn(1).setHeaderValue("Администратор");


        userTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {

                    public void valueChanged(ListSelectionEvent e) {
                        if (!e.getValueIsAdjusting()) {

                            // Получаем индекc в таблице
                            int tableSelectedRow = userTable.getSelectedRow();

                            if (tableSelectedRow > -1) {
                                // Получаем реальный индекс в модели
                                int modelSelectedRow = userTable.convertRowIndexToModel(tableSelectedRow);
                                String s = (String) userTable.getModel().getValueAt(modelSelectedRow, 4);
                                descriptionTextArea.setText(s);
                            } else {
                                descriptionTextArea.setText("");
                            }
                        }
                    }
                });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoCompleteDecorator1 = new org.jdesktop.swingx.autocomplete.AutoCompleteDecorator();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new minersinstrument.ui.ADBJXTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        userTable.setName("userTable"); // NOI18N
        jScrollPane1.setViewportView(userTable);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(UsersMainPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        descriptionTextArea.setName("descriptionTextArea"); // NOI18N
        jScrollPane2.setViewportView(descriptionTextArea);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getActionMap(UsersMainPanel.class, this);
        addButton.setAction(actionMap.get("addNewUser")); // NOI18N
        addButton.setName("addButton"); // NOI18N

        editButton.setAction(actionMap.get("editCurrentUser")); // NOI18N
        editButton.setName("editButton"); // NOI18N

        jButton3.setAction(actionMap.get("changePassword")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N

        delButton.setAction(actionMap.get("delCurrentUser")); // NOI18N
        delButton.setName("delButton"); // NOI18N

        jButton1.setAction(actionMap.get("setUserAccessSetup")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(delButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void addNewUser() {
        userTable.addRow();
    }

    @Action
    public void editCurrentUser() {
        adapter.setSetPassword(false);
        userTable.editRow();
    }

    @Action
    public void delCurrentUser() {
        userTable.delRow();
    }

    @Action
    public void changePassword() {
        adapter.setSetPassword(true);
        userTable.editRow();
    }

    @Action
    public void setUserAccessSetup() {
        int currRow = userTable.getCurrentRowIndexForModel();

        int userId = -1;
        try {
            userId = (Integer) adapter.getValueAt(currRow, 0);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Выберите пользователя.",
                    "Информация...",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        AccessSetup p =
                new AccessSetup(userId);
        AUniversalDialog d = new AUniversalDialog(p, null, true);
        d.setTitleIcon(new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/privelegii.png")));
        d.setTitle("Настройка права пользователя...");
        d.setTitleText("Пользователь - " + adapter.getValueAt(currRow, 1));

        d.setVisible(true);
        d.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private org.jdesktop.swingx.autocomplete.AutoCompleteDecorator autoCompleteDecorator1;
    private javax.swing.JButton delButton;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private minersinstrument.ui.ADBJXTable userTable;
    // End of variables declaration//GEN-END:variables
}
