/*
 * ProductsControlPanel.java
 *
 * Created on 19 Февраль 2008 г., 23:04
 */
package tradeterminal.products;

import java.awt.Dimension;
import java.sql.Types;
import java.util.List;
import javax.swing.Icon;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import minersinstrument.db.ADBProc;
import minersinstrument.db.ADBProcParametr;
import minersinstrument.db.PADBUtils;
import minersinstrument.ui.ADialog;
import minersinstrument.ui.ANumbericCellRenderer;
import minersinstrument.ui.AUniversalDialog;
import minersinstrument.ui.IADialogPanel;
import org.jdesktop.application.Action;
import tradeterminal.IPage;
import tradeterminal.Setup;
import tradeterminal.conf.AppAccessSettings;
import tradeterminal.products_groups.IUpdateForID;

/**
 *
 * @author  kopychenko
 */
public class ProductsMainPanel extends javax.swing.JPanel
        implements IUpdateForID, IPage, IADialogPanel {

    ProductsAdapter adapter = new ProductsAdapter(Setup.getSource());

    /** Creates new form ProductsControlPanel */
    public ProductsMainPanel() {
        initComponents();

        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(32, 32));
        jScrollPane1.getHorizontalScrollBar().setPreferredSize(new Dimension(32, 32));

//        jScrollPane2.getVerticalScrollBar().setPreferredSize(new Dimension(32,32));
//        jScrollPane2.getHorizontalScrollBar().setPreferredSize(new Dimension(32,32));

        productsTable.setAdapter(adapter);

        productsTable.getColumnModel().removeColumn(productsTable.getColumnModel().getColumn(0));
        productsTable.getColumnModel().removeColumn(productsTable.getColumnModel().getColumn(4));

        productsTable.getColumnModel().getColumn(0).setMinWidth(100);
        productsTable.getColumnModel().getColumn(0).setHeaderValue("Наименование");
        productsTable.getColumnModel().getColumn(1).setHeaderValue("Описание");
        productsTable.getColumnModel().getColumn(2).setHeaderValue("Штрихкод");
        productsTable.getColumnModel().getColumn(3).setHeaderValue("Количество");
        productsTable.getColumnModel().getColumn(4).setHeaderValue("Мера");
        productsTable.getColumnModel().getColumn(5).setHeaderValue("Цена");
        productsTable.getColumnModel().getColumn(6).setHeaderValue("<html><body>Специальная<br>цена</body></html>");

        productsTable.getColumnModel().getColumn(6).setCellRenderer(
                new ANumbericCellRenderer(new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/16X16/spskidka.png"))));

        productsTable.getColumnModel().getColumn(7).setHeaderValue("<html><body>Процентная<br>скидка %</body></html>");
        productsTable.getColumnModel().getColumn(7).setCellRenderer(
                new ANumbericCellRenderer(new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/16X16/prskidka.png")), "", "%"));

        productsTable.getColumnModel().getColumn(8).setHeaderValue("<html><body>Итоговая цена<br> за 1 меру</body></html>");
        productsTable.getColumnModel().getColumn(9).setHeaderValue("<html><body>Итоговая цена<br>за все</body></html>");


        productsTable.getSelectionModel().addListSelectionListener(
                new ListSelectionListener() {

                    public void valueChanged(ListSelectionEvent e) {
                        if (!e.getValueIsAdjusting()) {
                            //tabloFormattedTextField.setValue(model.getSummForAllProducts());

                            int tableSelectedRow = productsTable.getSelectedRow();

                            if (tableSelectedRow != -1) { // Если элемент всеже выбран
                                // Получаем реальный индекс в модели
                                int modelSelectedRow = productsTable.convertRowIndexToModel(tableSelectedRow);

                                selectedRowId = ((Number) adapter.getValueAt(modelSelectedRow, 0)).intValue();
                                selectedScode = (String) adapter.getValueAt(modelSelectedRow, 3);
                            }
                        }
                    }
                });

        progectsGroupsPanel1.addUpdatedForIdElement(this);
    }

    /**
     * Отобразить кнопки редактирования
     * @param visible
     */
    public void setVisibleEditBattons(boolean visible) {
        progectsGroupsPanel1.setVisibleEditBattons(visible);
        buttonPanel.setVisible(visible);

    }
    private int selectedRowId = -1;
    private String selectedScode;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        centralPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new minersinstrument.ui.ADBJXTable();
        updateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        progectsGroupsPanel1 = new tradeterminal.products_groups.ProgectsGroupsMainPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        centralPanel.setName("centralPanel"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        productsTable.setName("productsTable"); // NOI18N
        productsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productsTable);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getActionMap(ProductsMainPanel.class, this);
        updateButton.setAction(actionMap.get("updateRecords")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tradeterminal.TradeTerminalApp.class).getContext().getResourceMap(ProductsMainPanel.class);
        updateButton.setText(resourceMap.getString("updateButton.text")); // NOI18N
        updateButton.setName("updateButton"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setAction(actionMap.get("findProductForSCod")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        javax.swing.GroupLayout centralPanelLayout = new javax.swing.GroupLayout(centralPanel);
        centralPanel.setLayout(centralPanelLayout);
        centralPanelLayout.setHorizontalGroup(
            centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addGroup(centralPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addComponent(updateButton)))
                .addContainerGap())
        );
        centralPanelLayout.setVerticalGroup(
            centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centralPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateButton)
                    .addGroup(centralPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(centralPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setName("buttonPanel"); // NOI18N
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        addButton.setAction(actionMap.get("addRecord")); // NOI18N
        addButton.setName("addButton"); // NOI18N
        buttonPanel.add(addButton);

        editButton.setAction(actionMap.get("editRecord")); // NOI18N
        editButton.setName("editButton"); // NOI18N
        buttonPanel.add(editButton);

        delButton.setAction(actionMap.get("delRecord")); // NOI18N
        delButton.setName("delButton"); // NOI18N
        buttonPanel.add(delButton);

        jPanel1.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanel1);

        progectsGroupsPanel1.setName("progectsGroupsPanel1"); // NOI18N
        jSplitPane1.setLeftComponent(progectsGroupsPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void productsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsTableMouseClicked
        if (evt.getClickCount() == 2) {

            Object o = this;
            do {
                if (o instanceof JComponent) {
                    o = ((JComponent) o).getParent();
                } else {
                    return;
                }
            } while (!(o instanceof ADialog));

            ADialog d = (ADialog) o;
            d.setReturnStatus(ADialog.RET_OK);
            d.setVisible(false);
        }
    }//GEN-LAST:event_productsTableMouseClicked

    @Action
    public void addRecord() {

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RB_EDIT)) {
            return;
        }

        productsTable.addRow();
    }

    @Action
    public void editRecord() {

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RB_EDIT)) {
            return;
        }

        productsTable.editRow();
    }

    @Action
    public void delRecord() {

        // Проверка прав доступа
        if (!AppAccessSettings.isCurrentUserHasAccessWithMessage(
                AppAccessSettings.RB_EDIT)) {
            return;
        }

        productsTable.delRow();
    }

    @Action
    public void updateRecords() {
        productsTable.updateRows();
    }

    // Обновление по id группы
    public void updateForId(int id) {
        adapter.update(id);
    }

    public void updateContent() {
        productsTable.updateRows();
    }

    @Override
    public Icon getCaptionIcon() {
        return new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/tovary.png"));
    }

    @Override
    public String getCaptionText() {
        return "Справочник товаров";
    }

    public List<JMenuItem> getMenuItemList() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Action
    public void findProductForSCod() {
        ReturnTheProductForScodDlPanel p = new ReturnTheProductForScodDlPanel();
        AUniversalDialog d = new AUniversalDialog(p, null, true);
        d.setTitleIcon(new javax.swing.ImageIcon(getClass().getResource("/tradeterminal/icons/TT_icons/32X32/poiskpokodu.png")));

        d.setVisible(true);
        d.dispose();

        if (d.getReturnStatus() == ADialog.RET_OK) {

            ADBProc proc = new ADBProc("find_product_id_for_scod");
            proc.addInParametr(new ADBProcParametr(Types.VARCHAR, p.getScod()));

            int id = PADBUtils.getIntScalar(Setup.getSource(), proc);

//            System.out.println(id);

            proc = new ADBProc("find_product_group_id_for_product_scod");
            proc.addInParametr(new ADBProcParametr(Types.VARCHAR, p.getScod()));

            int groupId = PADBUtils.getIntScalar(Setup.getSource(), proc);

            System.out.println(groupId);

            progectsGroupsPanel1.setSelectedGroupId(groupId);

            int tSelectIndex = adapter.geModelIdForProductId(id);

            int tableIndex = productsTable.convertRowIndexToView(tSelectIndex);
            productsTable.setRowSelectionInterval(tableIndex, tableIndex);

            productsTable.scrollRowToVisible(productsTable.getSelectedRow());
            productsTable.repaint();

        }
    }

    /**
     * Получить id выбранного товара
     * @return
     */
    public int getSelectedRowId() {
        return selectedRowId;
    }

    /**
     * Получть код выбранного товара
     * @return
     */
    public String getSelectedScode() {
        return selectedScode;
    }

    public boolean checkPanel() {

        if (selectedRowId == -1) {
            JOptionPane.showMessageDialog(this, "Выберите товар.", "Внимание...", JOptionPane.WARNING_MESSAGE);
            return false;
        } else {
            return true;
        }
    }

    public void openPanel() {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JButton delButton;
    private javax.swing.JButton editButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private minersinstrument.ui.ADBJXTable productsTable;
    private tradeterminal.products_groups.ProgectsGroupsMainPanel progectsGroupsPanel1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}



